---
- name: Ensure caddy is installed (dnf)
  dnf:
    name: caddy
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: ensure caddy is installed (apt)
  apt:
    name: caddy
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: ensure https traffic is allowed
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true

- name: ensure http traffic is allowed
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: ensure Caddy service is enabled
  service:
    name: caddy
    state: started
    enabled: true

- name: copy main Caddyfile
  copy:
    src: caddy_confs/Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: root
    mode: 0644
  notify: restart caddy
